- charmander-domain/charmander-domain-common/src/main/java/org/cm/domain/common/Term.java
- charmander-domain/charmander-domain-common/src/main/java/org/cm/domain/member/MemberTermAgreement.java
- charmander-domain/charmander-domain-common/src/main/java/org/cm/domain/term/Term.java
> refactor: Term 엔티티 리팩토링

- build.gradle
- charmander-api/charmander-api-common/build.gradle
- charmander-api/charmander-api-core/build.gradle
- charmander-infra/charmander-docs/build.gradle
- settings.gradle
> build: api 모듈 및 docs모듈 추가

- build.gradle
- charmander-infra/charmander-docs/build.gradle
- charmander-infra/charmander-docs/src/main/java/org/cm/infra/docs/DocumentMetadata.java
- charmander-infra/charmander-docs/src/main/java/org/cm/infra/docs/SwaggerConfig.java
- charmander-infra/charmander-docs/src/main/resources/api-docs.yml
> feat: 스웨거 설정 추가

- charmander-common/src/main/java/org/cm/common/exception/ExceptionCode.java
- charmander-common/src/main/java/org/cm/common/exception/WebExceptionCode.java
- charmander-domain/charmander-domain-common/build.gradle
- charmander-domain/charmander-domain-common/src/main/java/org/cm/domain/common/GenericEnumConverter.java
- charmander-domain/charmander-domain-common/src/main/java/org/cm/domain/exception/CommonDomainException.java
- charmander-domain/charmander-domain-common/src/main/java/org/cm/domain/exception/CommonDomainExceptionCode.java
- charmander-domain/charmander-domain-core/build.gradle
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/task/Task.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/template/Template.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/exception/CoreDomainException.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/exception/CoreDomainExceptionCode.java
> feat: 도메인 예외 객체 정의, 및 변경 적용

- charmander-api/charmander-api-core/build.gradle
- charmander-api/charmander-api-core/src/main/java/org/cm/api/CoreExceptionAdvice.java
- charmander-common/src/main/java/org/cm/common/exception/ExceptionCode.java
> feat: 전역 예외 핸들러 추가

- charmander-api/charmander-api-core/src/main/java/org/cm/web/resolver/AuthUserResolver.java
- resolves #68
---
- Authorization 헤더가 없을 때 NPE가 발생하는 문제 해결
- 
-
> fix: AuthUserResolver NPE

- charmander-api/charmander-api-core/build.gradle
- resolves #67
---
- 유실된 Redis 의존성 다시 추가. 
- 
- 어쩌다 사라졌을까...?
> fix: Add Missing Redis dependency

- charmander-api/charmander-api-common/src/main/java/org/cm/api/common/dto/ListResponse.java
- charmander-api/charmander-api-common/src/main/java/org/cm/api/common/dto/PageResponse.java
- resolves #75
---
- 공통 응답 DTO 클래스 작성
- 
-
> feat: 공통 응답 DTO 클래스 작성

- build.gradle
- gradle/libs.versions.toml
- resolves #76
---
- Mapstruct 의존성 설정 
- 
-
> feat: MapStruct 의존성 설정

- build.gradle
- charmander-common/src/main/java/org/cm/common/domain/File.java
- charmander-common/src/main/java/org/cm/common/domain/FileType.java
- charmander-common/src/main/java/org/cm/common/exception/BaseExceptionCode.java
- charmander-common/src/main/java/org/cm/common/utils/RandomKeyGenerator.java
- charmander-infra/charmander-file-strorage/build.gradle
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/PropertyScanner.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/storage/AwsProperty.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/storage/AwsSingleFileUploadService.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/storage/ContentsLocator.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/storage/S3Config.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/storage/SingleFileUploadService.java
- charmander-infra/charmander-file-strorage/src/main/resources/file-storage.yml
- charmander-infra/charmander-file-strorage/src/test/java/org/cm/Application.java
- charmander-infra/charmander-file-strorage/src/test/java/org/cm/infra/storage/ContentsLocatorTest.java
- charmander-infra/charmander-file-strorage/src/test/resources/application.yml
- settings.gradle
> feat: 단일 파일 업로드 기능 추가

- charmander-api/charmander-api-core/build.gradle
- charmander-api/charmander-api-core/src/main/java/org/cm/api/template/TemplateController.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/template/TemplateService.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/template/TemplateSuggestService.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/template/dto/TemplateCategoryDto.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/template/dto/TemplateResponse.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/template/dto/TemplateSuggestAIResult.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/template/dto/TemplateSuggestRequest.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/template/dto/TemplateSuggestResponse.java
- charmander-api/charmander-api-core/src/main/java/org/cm/config/AIConfig.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/template/TemplateCategory.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/template/TemplateRepository.java
- resolves #51
---
- 
- 
- Tool Calling이 안돼는 문제가 있어서 Prompt에 직접 넣었음.
- Template 추천을 위한 backoffice API 또는 수작업이 필요함.
> [구현] Template 

- charmander-api/charmander-api-common/src/main/java/org/cm/jwt/JwtConfig.java
> [기타] 로컬 개발을 위한 RSA 키 생성

- charmander-api/charmander-api-core/src/main/java/org/cm/api/project/ProjectController.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/project/ProjectService.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/project/dto/ProjectDetailResponse.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/project/dto/ProjectResponse.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/project/dto/ProjectUpdateRequest.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/project/Project.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/project/ProjectRepository.java
> [구현] Project Entity CRUD

- charmander-api/charmander-api-core/src/main/java/org/cm/api/task/TaskController.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/task/TaskService.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/task/dto/TaskResponse.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/task/TaskRepository.java
> [구현] Task Entity CRUD

- .github/workflows/deploy.yml
- charmander-api/charmander-api-core/Dockerfile
> dev-server API-Core CI/CD 구축

- charmander-api/charmander-api-video/build.gradle
- charmander-api/charmander-api-video/src/main/java/org/cm/Application.java
- charmander-api/charmander-api-video/src/main/java/org/cm/api/VideoController.java
- charmander-api/charmander-api-video/src/main/resources/application.yaml
- settings.gradle
> build: 영상 생성 처리 서버 설정

- .github/workflows/deploy.yml
- charmander-api/charmander-api-core/appspec.yml
- scripts/start-server.sh
> API-Core CICD 구조 변경

- .github/workflows/deploy.yml
> hotfix: deploy.yml파일 수정

- .github/workflows/deploy_api.yml
- .github/workflows/deploy_dev.yml
- charmander-api/charmander-api-core/Dockerfile
- scripts/start-server.sh
> API-Core Production CICD 구축

- .github/workflows/deploy_api.yml
- charmander-api/charmander-api-core/Dockerfile
> API-Core CICD dockerfile, deploy file 수정

- charmander-api/charmander-api-video/build.gradle
- charmander-api/charmander-api-video/src/main/java/org/cm/api/TaskCompleteRequest.java
- charmander-api/charmander-api-video/src/main/java/org/cm/api/TaskController.java
- charmander-api/charmander-api-video/src/main/java/org/cm/config/TaskConfig.java
- charmander-api/charmander-api-video/src/main/java/org/cm/service/TaskService.java
- charmander-api/charmander-api-video/src/main/java/org/cm/vo/TtsCreateCommand.java
- charmander-api/charmander-api-video/src/test/java/org/cm/fixture/ProjectFixture.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/task/Task.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/task/TaskOutput.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/exception/CoreDomainExceptionCode.java
- charmander-infra/charmander-file-strorage/build.gradle
> feat: TTS 생성 요청에 서명 상태를 전달하도록 변경

- README.md
> docs: aws 다이어그램(v1)

- charmander-api/charmander-api-core/src/test/java/org/cm/api/account/AccountServiceTest.java
> fix: 이메일 검증 이력이 없을 경우 예외 발생

- charmander-api/charmander-api-core/src/main/java/org/cm/security/auth/oauth/OAuthUserInfo.java
> fix: OAuthUserInfo.java casting error

- charmander-api/charmander-api-core/build.gradle
- charmander-api/charmander-api-core/src/main/resources/bootstrap.yml
- charmander-domain/charmander-domain-common/src/main/resources/db-common.yml
> secret manager 환경설정 및 구축

- appspec.yml
- charmander-api/charmander-api-core/build.gradle
- scripts/start-server.sh
> 블루그린 무중단 배포 구축

- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/scene/Scene.java
- resolves #hotfix
---
- 
- 
-
> hotfix: background 컬럼 이름 중복 임시 수정

- charmander-infra/charmander-file-strorage/build.gradle
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/mediaconvert/queue/WavCombineQueue.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/property/BucketProperty.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/property/MediaConvertProperty.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/property/S3URLProperty.java
> feat: 여러 wav를 묶어 하나의 wav 파일로 변환하도록 요청 기능 구현

- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/mediaconvert/AwsMediaConvertConfiguration.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/mediaconvert/queue/AllVideoCombineQueue.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/mediaconvert/queue/VideoOverlayCombineQueue.java
> feat: 모든 영상을 하나로 엮고, 영상 위에 영상을 덮는 기능 미디어 컨버터 큐 정의

- charmander-api/charmander-api-video/src/main/java/org/cm/service/TaskScriptEventListener.java
- charmander-api/charmander-api-video/src/main/java/org/cm/vo/TtsCombineEvent.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/converter/InputSchemaConverter.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/scene/SceneMedia.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/scene/SceneMediaType.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/task/Task.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/task/TaskInputSchema.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/taskscript/TaskScript.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/taskscript/TaskScriptRepository.java
> feat: tts 결합을 담당하는 이벤트 리스너 구현

- charmander-common/src/main/java/org/cm/common/domain/SceneMediaType.java
> feat: sceneMediaType 추가

- .github/workflows/deploy-dev-oci.yml
> fix: 내 프로필 조회 phone 필드 누락 

- charmander-api/charmander-api-video/src/main/java/org/cm/api/TtsCombineConsumer.java
- charmander-api/charmander-api-video/src/main/java/org/cm/api/TtsCombineRecord.java
- charmander-api/charmander-api-video/src/main/java/org/cm/service/TaskScriptEventListener.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/converter/SceneConverter.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/task/SceneOutput.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/task/SceneOutputRepository.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/mediaconvert/queue/WavVideoCombineQueue.java
> feat: tts와 음성과 비디오, 이미지를 결합하는 컨슈머 추가

- charmander-api/charmander-api-core/src/main/java/org/cm/api/template/dto/TemplateResponse.java
- charmander-api/charmander-api-core/src/test/java/org/cm/api/template/TemplateControllerTest.java
- charmander-api/charmander-api-core/src/test/java/org/cm/test/config/BaseWebMvcUnitTest.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/template/TemplateAvatar.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/template/TemplateAvatarType.java
- charmander-domain/charmander-domain-core/src/testFixtures/java/org/cm/test/fixture/TemplateFixture.java
> feat: TemplateAvatar size 속성 추가

- charmander-api/charmander-api-core/src/main/java/org/cm/api/template/dto/TemplateResponse.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/template/TemplateData.java
> feat: 템플릿 대표이미지 컬럼 추가

- charmander-api/charmander-api-core/src/main/java/org/cm/api/project/dto/ProjectDetailResponse.java
> fix: ProjectDetailResponse 'data' 필드 삭제

- charmander-api/charmander-api-core/src/main/java/org/cm/api/template/dto/TemplateResponse.java
- charmander-api/charmander-api-core/src/test/java/org/cm/api/template/TemplateControllerUnitTest.java
- charmander-domain/charmander-domain-core/src/testFixtures/java/org/cm/test/fixture/TemplateFixture.java
> fix: Template 목록 반환할 때 카테고리 Id 반환하게 수정

- charmander-api/charmander-api-core/src/main/java/org/cm/domain/taskscript/TaskScriptFactory.java
- charmander-api/charmander-api-video/src/main/java/org/cm/api/ConvertCompleteConsumer.java
- charmander-api/charmander-api-video/src/main/java/org/cm/api/SceneCombineConsumer.java
- charmander-api/charmander-api-video/src/main/java/org/cm/api/TaskConsumer.java
- charmander-api/charmander-api-video/src/main/java/org/cm/api/TtsCombineConsumer.java
- charmander-api/charmander-api-video/src/main/java/org/cm/api/VideoConcatConsumer.java
- charmander-api/charmander-api-video/src/main/java/org/cm/service/TaskScriptEventListener.java
- charmander-domain/charmander-domain-core/build.gradle
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/task/SceneOutput.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/task/Task.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/taskscript/TaskScript.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/taskscript/TaskScriptRepository.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/mediaconvert/queue/AllVideoCombineQueue.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/mediaconvert/queue/WavCombineQueue.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/mediaconvert/queue/WavImageCombineQueue.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/mediaconvert/queue/WavVideoCombineQueue.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/mediaconvert/queue/impl/AwsWavCombineQueue.java
- charmander-infra/charmander-file-strorage/src/main/java/org/cm/infra/utils/MetadataConverter.java
- charmander-infra/charmander-kafka/src/main/java/org/cm/kafka/KafkaConsumerConfig.java
- charmander-infra/charmander-kafka/src/main/java/org/cm/kafka/UserMetadata.java
> feat: 영상 생성 기능 구현

- charmander-api/charmander-api-core/src/main/java/org/cm/api/project/ProjectController.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/project/ProjectService.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/project/Project.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/project/ProjectRepository.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/scene/Scene.java
- charmander-domain/charmander-domain-core/src/main/java/org/cm/domain/scene/SceneTranscript.java
> fix: Project 조회 Multiple Bag 문제 수정

- charmander-api/charmander-api-core/src/main/java/org/cm/api/template/TemplateSuggestService.java
> fix: java.lang.ClassFormatError at TemplateSuggestService

- charmander-api/charmander-api-core/src/main/java/org/cm/api/project/ProjectController.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/project/ProjectSummaryService.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/project/dto/ProjectGenerateTranscriptAIResult.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/project/dto/ProjectGenerateTranscriptRequest.java
> feat: 기사 대본 생성 API

- charmander-api/charmander-api-core/src/main/java/org/cm/api/scene/SceneTranscriptController.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/scene/SceneTranscriptService.java
- charmander-api/charmander-api-core/src/main/java/org/cm/api/scene/dto/SceneTranscriptDeleteCommand.java
- charmander-api/charmander-api-core/src/test/java/org/cm/api/scene/SceneTranscriptServiceIntergrationTest.java
- charmander-api/charmander-api-core/src/test/java/org/cm/test/config/BaseServiceIntergrationTest.java
- charmander-domain/charmander-domain-core/src/testFixtures/java/org/cm/test/fixture/SceneTranscriptFixture.java
> feat: 대본 삭제 API

- .github/workflows/deploy_api.yml
- charmander-api/charmander-api-core/Dockerfile
> whatap 에이전트 배포 스크립트 작성
